# Generated by Django 6.0.2 on 2026-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='movies/'),
        ),
    ]
