# Generated by Django 6.0.2 on 2026-08-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitles',
            field=models.TextField(blank=True, help_text='ఫార్మాట్: start-end|text (ఒక్కో లైన్ కి ఒక subtitle). ఉదా: 0-5|Welcome to the movie'),
        ),
    ]
