# Generated by Django 6.0.2 on 2026-08-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movie_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_kids',
            field=models.BooleanField(default=False, verbose_name='Kids Profile'),
        ),
    ]
