# Generated by Django 6.0.2 on 2026-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile_is_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=10),
        ),
    ]
